<?xml version="1.0" encoding="utf-8"?><Database Name="CPM" EntityNamespace="CPM.DAL" ContextNamespace="CPM.DAL" Class="CPMmodel" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=CPM;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CPMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ClaimDetail" Member="ClaimDetails">
    <Type Name="ClaimDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DOT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TDRemaining" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TDOriginal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="RemainingTread" Type="System.Decimal" DbType="Decimal(38,16)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NatureOfDefect" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPrice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreditAmt" Type="System.Decimal" DbType="Decimal(38,6)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CurrentCost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceAmt" Type="System.Decimal" DbType="Decimal(38,6)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ply" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ClaimDetail_FileDetail" Member="FileDetails" ThisKey="ID" OtherKey="ClaimDetailID" Type="FileDetail" />
      <Association Name="MasterDefect_ClaimDetail" Member="MasterDefect" AccessModifier="Internal" ThisKey="NatureOfDefect" OtherKey="ID" Type="MasterDefect" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Claim_ClaimDetail" Member="Claim" AccessModifier="Internal" ThisKey="ClaimID" OtherKey="ID" Type="Claim" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Member="Comment1" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Claim_Comment" Member="Claim" AccessModifier="Internal" ThisKey="ClaimID" OtherKey="ID" Type="Claim" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerLocation" Member="CustomerLocations">
    <Type Name="CustomerLocation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CustomerLocation_UserLocation" Member="UserLocations" ThisKey="ID" OtherKey="LocID" Type="UserLocation" />
      <Association Name="MasterOrg_CustomerLocation" Member="MasterOrg" ThisKey="CustomerId" OtherKey="ID" Type="MasterOrg" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ERPCustomerLocation" Member="ERPCustomerLocations">
    <Type Name="ERPCustomerLocation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ERPCustomerOrg" Member="ERPCustomerOrgs">
    <Type Name="ERPCustomerOrg">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ERPMasterBrand" Member="ERPMasterBrands">
    <Type Name="ERPMasterBrand">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ERPMasterInventory" Member="ERPMasterInventories">
    <Type Name="ERPMasterInventory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="BrandID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ply" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TDOriginal" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentCost" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ERPUsers" Member="ERPUsers">
    <Type Name="ERPUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrgCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FileDetail" Member="FileDetails">
    <Type Name="FileDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimDetailID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploadedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ClaimDetail_FileDetail" Member="ClaimDetail" AccessModifier="Internal" ThisKey="ClaimDetailID" OtherKey="ID" Type="ClaimDetail" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="MasterFileTypeDetail_FileDetail" Member="MasterFileTypeDetail" AccessModifier="Internal" ThisKey="FileType" OtherKey="ID" Type="MasterFileTypeDetail" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FileHeader" Member="FileHeaders">
    <Type Name="FileHeader">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UploadedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MasterFileTypeHeader_FileHeader" Member="MasterFileTypeHeader" AccessModifier="Internal" ThisKey="FileType" OtherKey="ID" Type="MasterFileTypeHeader" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Claim_FileHeader" Member="Claim" AccessModifier="Internal" ThisKey="ClaimID" OtherKey="ID" Type="Claim" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MasterActivity" Member="MasterActivities">
    <Type Name="MasterActivity">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MasterActivity_ActivityHistory" Member="ActivityHistories" ThisKey="ID" OtherKey="ActivityID" Type="ActivityHistory" />
    </Type>
  </Table>
  <Table Name="dbo.MasterClaimStatus" Member="MasterClaimStatus">
    <Type Name="MasterClaimStatus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MasterClaimStatus_StatusHistory" Member="StatusHistories" ThisKey="ID" OtherKey="NewStatusID" Type="StatusHistory" />
    </Type>
  </Table>
  <Table Name="dbo.MasterDefect" Member="MasterDefects">
    <Type Name="MasterDefect">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MasterDefect_ClaimDetail" Member="ClaimDetails" ThisKey="ID" OtherKey="NatureOfDefect" Type="ClaimDetail" />
    </Type>
  </Table>
  <Table Name="dbo.MasterFileTypeDetail" Member="MasterFileTypeDetails">
    <Type Name="MasterFileTypeDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MasterFileTypeDetail_FileDetail" Member="FileDetails" ThisKey="ID" OtherKey="FileType" Type="FileDetail" />
    </Type>
  </Table>
  <Table Name="dbo.MasterFileTypeHeader" Member="MasterFileTypeHeaders">
    <Type Name="MasterFileTypeHeader">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MasterFileTypeHeader_FileHeader" Member="FileHeaders" ThisKey="ID" OtherKey="FileType" Type="FileHeader" />
    </Type>
  </Table>
  <Table Name="dbo.MasterInventory" Member="MasterInventories">
    <Type Name="MasterInventory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="BrandId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ply" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TDOriginal" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentCost" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="MasterBrand_MasterInventory" Member="MasterBrand" ThisKey="BrandId" OtherKey="ID" Type="MasterBrand" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.MasterOrgType" Member="MasterOrgTypes">
    <Type Name="MasterOrgType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MasterOrgType_MasterOrg" Member="MasterOrgs" ThisKey="ID" OtherKey="OrgTypeId" Type="MasterOrg" />
    </Type>
  </Table>
  <Table Name="dbo.StatusHistory" Member="StatusHistories">
    <Type Name="StatusHistory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OldStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MasterClaimStatus_StatusHistory" Member="MasterClaimStatus" ThisKey="NewStatusID" OtherKey="ID" Type="MasterClaimStatus" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Claim_StatusHistory" Member="Claim" ThisKey="ClaimID" OtherKey="ID" Type="Claim" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLocation" Member="UserLocations">
    <Type Name="UserLocation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CustomerLocation_UserLocation" Member="CustomerLocation" ThisKey="LocID" OtherKey="ID" Type="CustomerLocation" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Users_UserLocation" Member="Users" ThisKey="UserID" OtherKey="ID" Type="Users" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ClaimDetail_Item_Defect" Member="vw_ClaimDetail_Item_Defects">
    <Type Name="vw_ClaimDetail_Item_Defect">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Serial" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DOT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TDRemaining" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="TDOriginal" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="RemainingTread" Type="System.Decimal" DbType="Decimal(38,16)" CanBeNull="true" />
      <Column Name="NatureOfDefect" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CreditAmt" Type="System.Decimal" DbType="Decimal(38,12)" CanBeNull="true" />
      <Column Name="CurrentCost" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceAmt" Type="System.Decimal" DbType="Decimal(38,12)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ply" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ItemCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Defect" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CustLoc_User_UserLoc" Member="vw_CustLoc_User_UserLocs">
    <Type Name="vw_CustLoc_User_UserLoc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsrLocID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CustOrg_Locs" Member="vw_CustOrg_Locs">
    <Type Name="vw_CustOrg_Loc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Locs" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_MasterOrg_Role" Member="vw_MasterOrg_Roles">
    <Type Name="vw_MasterOrg_Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="OrgTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityHistory" Member="ActivityHistories">
    <Type Name="ActivityHistory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserText" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ActDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="MasterActivity_ActivityHistory" Member="MasterActivity" ThisKey="ActivityID" OtherKey="ID" Type="MasterActivity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Users_ActivityHistory" Member="Users" ThisKey="UserID" OtherKey="ID" Type="Users" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_ActivityLog" Member="vw_ActivityLogs">
    <Type Name="vw_ActivityLog">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserText" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ActDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimText" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Activity" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MasterOrg" Member="MasterOrgs">
    <Type Name="MasterOrg">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="OrgTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalespersonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MasterOrg_CustomerLocation" Member="CustomerLocations" ThisKey="ID" OtherKey="CustomerId" Type="CustomerLocation" />
      <Association Name="MasterOrg_Claim" Member="Claims" ThisKey="ID" OtherKey="CustID" Type="Claim" />
      <Association Name="MasterOrgType_MasterOrg" Member="MasterOrgType" ThisKey="OrgTypeId" OtherKey="ID" Type="MasterOrgType" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MasterSetting" Member="MasterSettings">
    <Type Name="MasterSetting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Setting" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SalespersonCode" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Users_UserLocation" Member="UserLocations" ThisKey="ID" OtherKey="UserID" Type="UserLocation" />
      <Association Name="Users_ActivityHistory" Member="ActivityHistories" ThisKey="ID" OtherKey="UserID" Type="ActivityHistory" />
      <Association Name="MasterRole_Users" Member="MasterRole" ThisKey="RoleID" OtherKey="ID" Type="MasterRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Users_Role_Org" Member="vw_Users_Role_Orgs">
    <Type Name="vw_Users_Role_Org">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalespersonCode" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrgType" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="OrgName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedByName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_StatusHistory_Usr" Member="vw_StatusHistory_Usrs">
    <Type Name="vw_StatusHistory_Usr">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OldStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NewStatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OldStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NewStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_CustOrg_SalesUser" Member="vw_CustOrg_SalesUsers">
    <Type Name="vw_CustOrg_SalesUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="SalespersonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrgTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Claim" Member="Claims">
    <Type Name="Claim">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimNo" Type="System.Int32" DbType="Int NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CustRefNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipToLocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BrandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalespersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Claim_ClaimDetail" Member="ClaimDetails" ThisKey="ID" OtherKey="ClaimID" Type="ClaimDetail" />
      <Association Name="Claim_Comment" Member="Comments" ThisKey="ID" OtherKey="ClaimID" Type="Comment" />
      <Association Name="Claim_FileHeader" Member="FileHeaders" ThisKey="ID" OtherKey="ClaimID" Type="FileHeader" />
      <Association Name="Claim_StatusHistory" Member="StatusHistories" ThisKey="ID" OtherKey="ClaimID" Type="StatusHistory" />
      <Association Name="MasterOrg_Claim" Member="MasterOrg" ThisKey="CustID" OtherKey="ID" Type="MasterOrg" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MasterRole" Member="MasterRoles">
    <Type Name="MasterRole">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrgTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManageRole" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ManageMaster" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ManageUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeleteClaim" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ViewActivity" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ManageSetting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ArchiveClaim" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanDelete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MasterRole_Users" Member="Users" ThisKey="ID" OtherKey="RoleID" Type="Users" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Yr_Claims_Items" Member="vw_Yr_Claims_Items">
    <Type Name="vw_Yr_Claims_Item">
      <Column Name="Yr" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MasterBrand" Member="MasterBrands">
    <Type Name="MasterBrand">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="MasterBrand_MasterInventory" Member="MasterInventories" ThisKey="ID" OtherKey="BrandId" Type="MasterInventory" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Brand_Items" Member="vw_Brand_Items">
    <Type Name="vw_Brand_Item">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Items" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Claim_Master_User_Loc" Member="vw_Claim_Master_User_Locs">
    <Type Name="vw_Claim_Master_User_Loc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClaimNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustRefNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipToLocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ClaimDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BrandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalespersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedToVal" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CustOrg" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="SalespersonName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vw_Claim_Dashboard" Member="vw_Claim_Dashboards">
    <Type Name="vw_Claim_Dashboard">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommentsExist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilesHExist" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustOrg" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ClaimNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustRefNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClaimDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ClaimDateOnly" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AssignedTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalespersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BrandID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Archived" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShipToLocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipToLoc" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ShipToCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Salesperson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AssignToName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>